
trigger:
- none

pool:
 
   name: Azure VM Agent Pool
   demands:
    - agent.name -equals Azure-Linux-VM-Agent-2
  
variables:
  - group: MIS-DOCKER-NILESH
   
resources:
 
  repositories:  
  - repository: mis-reusable
    type: github
    name: cybagedevops/mis-reusable
    endpoint: mis
    ref: main
stages:
  - stage: 
    jobs:
    - job: 
      steps:
        - template: .azure/pipelines/nilesh/DOCKERTEMPLATE.yml@mis-reusable
      
          parameters:
            azureSubscription: $(azureSubscription)
            aciName: 'projectserviceaci'
            appSettings: 'nileshQA'
            repository: 'mis-project-service-nilesh'
            dnsName: 'project-ci-service'
            acrName: $(acrName)
            registryPassword: $(registryPassword)
            resourceGroup: $(resourceGroup)
            SubscriptionId: $(SubscriptionId)
            keyVaultName: $(keyVaultName)
            resourceGroupNameKeyVault: $(resourceGroupNameKeyVault)
