
trigger:
- none
variables:
 - group: MIS-DB-NILESH
pool:
   name: Azure VM Agent Pool
  
    
resources:
  # pipelines:
  #   - pipeline: Previous-pipeline-trigger
  #     source: MIS-LEAVEMANAGEMENT-SERVICE-BUILD-DEPLOY-NILESH
  #     trigger: true
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main

stages:
- stage: 'QA'
  jobs:
    - job: 'QA'
      steps:
        - template: .azure/pipelines/nilesh/Db-Template.yml@mis-reusable
          parameters:
           azureSubscription: $(azureSubscription)
           projects: '**/MIS.Services.Project.Api.csproj'
           appName: 'mis-project-service-nilesh-qa'
           keyVaultName: 'mis-keyvault-nilesh'
           resourceGroupNameKeyVault: 'rg-mis-persistent'
           resourceGroupNameAppService: 'rg-mis-nilesh-QA'
           appSettings : 'nileshQA'
           buildProject: true

- stage: 'Prod'
  jobs:
    - job: 'Prod'
      steps:
        - template: .azure/pipelines/nilesh/Db-Template.yml@mis-reusable
          parameters:
           azureSubscription: $(azureSubscription)
           projects: '**/MIS.Services.Project.Api.csproj'
           appName: 'mis-project-service-nilesh-prod'
           keyVaultName: 'mis-keyvault-nileshvprod'
           resourceGroupNameKeyVault: 'rg-mis-persistent'
           resourceGroupNameAppService: 'rg-mis-nilesh-Prod'
           appSettings : 'nileshProd'
           buildProject: false