
name: MIS-PROJECT-SERVICE-BUILD-DEPLOY-NILESH
 
trigger:
- none
pool:
   name: MIS Agent Pool
   demands:
    - agent.name -equals mis-agent-nilesh
resources:
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main

steps:
  - template: .azure/pipelines/nilesh/MisSVCTemplate.yml@mis-reusable
    parameters:
     projects: '**/MIS.Services.Project.Api/MIS.Services.Project.Api.csproj'
     WebsiteName: 'mis-project-svc'