# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- none
pool:
   name: MIS Agent Pool
   demands:
    - agent.name -equals VAISHNAVIRA-VD3
resources:
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main

steps:
  - template: .azure/pipelines/vaishnavi/MIS-SVC-REUSABLE-IIS.yml@mis-reusable
    parameters:
     projects: '**/MIS.Services.Project.Api/MIS.Services.Project.Api.csproj'
     WebsiteName: 'mis-project-service'