# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool: 
 name: Azure VM Agent Pool
 demands:
   - agent.name -equals Azure-Linux-VM-Agent-2
  
variables:
  - group: MIS-DOCKER-VAISHNAVI
   
resources:
  repositories:  
  - repository: mis-reusable
    type: github
    name: cybagedevops/mis-reusable
    endpoint: mis
    ref: main
stages:
  - stage: 
    jobs:
    - job: 
      steps:
        - template: .azure/pipelines/vaishnavi/service-DockerImg-template.yml@mis-reusable
      
          parameters:
            azureSubscription: $(azureSubscription)
            aciName: 'mis-project-svc-vaishnavi'
            appSettings: 'vaishnaviQA'
            repository: 'mis-project-service-vaishnavi'
            dnsName: 'project-ci-svc'
            acrName: $(acrName)
            registryPassword: $(registryPassword)
            resourceGroup: $(resourceGroup)
            SubscriptionId: $(SubscriptionId)
            keyVaultName: $(keyVaultName)
            resourceGroupNameKeyVault: $(resourceGroupNameKeyVault)
