# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
   vmImage: ubuntu-latest
  
variables:
  - group: MIS-DOCKER-RK
   
resources:
  # pipelines:
  # - pipeline: Previous-pipeline-trigger
  #   source: MIS-TRAINING-SVC-DOCKER-RK
  #   trigger: true
  repositories:  
  - repository: mis-reusable
    type: github
    name: cybagedevops/mis-reusable
    endpoint: mis
    ref: main
stages:
  - stage: 
    jobs:
    - job: 
      steps:
        - template: .azure/pipelines/ravi/MIS-SERVICES-DOCKER-TEMPLATE-RK.yml@mis-reusable
      
          parameters:
            azureSubscription: $(azureSubscription)
            aciName: 'mis-project-svc-rk'
            appSettings: 'raviQA'
            repository: 'mis-project-service-ravi'
            dnsName: 'aci-project-svc'
            acrName: $(acrName)
            registryPassword: $(registryPassword)
            resourceGroup: $(resourceGroup)
            SubscriptionId: $(SubscriptionId)
            keyVaultName: $(keyVaultName)
            resourceGroupNameKeyVault: $(resourceGroupNameKeyVault)
