name: MIS-Project-SERVICE-BUILD-DEPLOY-RAVI-$(Year:yyyy).$(Month).$(DayOfMonth)-$(rev:rr)
 
trigger: none
 
pool: 
    name: MIS Agent Pool
    demands:
    - agent.name -equals self-hosted-agent-Rk


resources:
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main

steps:
  - template: .azure/pipelines/ravi/MIS-SVC-REUSABLE-IIS-RK.yml@mis-reusable
    parameters:
     projects: '**/MIS.Services.Project.Api/MIS.Services.Project.Api.csproj'
     WebsiteName: 'mis-project-service' 

            
