name: MIS-PROJECT-SVC-DOCKER-IMAGE-BUILD-RAVI-$(Year:yyyy).$(Month).$(DayOfMonth)-$(rev:rr)


trigger:
- none

pool:
   vmImage: ubuntu-latest
  
variables:
  - group: MIS-DOCKER-RK
   
resources:
  pipelines:
    - pipeline: Previous-pipeline-trigger
      source: MIS-RECRUITMENT-SVC-DOCKER-IMAGE-BUILD-RAVI
      trigger: true
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main
stages:
  - stage: 
    jobs:
    - job: 
      steps:
        - template: .azure/pipelines/ravi/MIS-SERVICES-REUSABLE-DOCKER-RK.yml@mis-reusable
          parameters:
            acrName: $(acrName)
            repository: 'mis-project-service-ravi'
            appSettings: 'raviQA'
            registryPassword: $(registryPassword)