name: MIS-PROJECT-SVC-BUILD-DEPLOY-$(Year:yyyy).$(Month).$(DayOfMonth)-$(rev:rr)
trigger: none


pool: 
 name: Azure VM Agent Pool

variables:
- name: artifactName
  value: 'mis-project-service' 

resources:
  pipelines:
    - pipeline: iac-rg-create-pipeline
      source: MIS-IAC-CREATE-RG-SHRIVIRAJ-20231027-01
      trigger: true
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main

stages:
- stage: BuildAndPackage
  jobs:
  - job: BuildAndPackage
    steps:
      - template: .azure/shriviraj/build-deploy-service-template.yml@mis-reusable
        parameters:         
           projectPath: '**/MIS.Services.Project.Api.csproj'
           #snykPath: '$(Build.SourcesDirectory)/MIS.Services.Project.Api/obj'
           artifactName: $(artifactName)


- stage: 'QA'
  jobs: 
  - job: 'QA'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
          buildType: 'current'
          artifactName: $(artifactName)
          targetPath: '$(Build.ArtifactStagingDirectory)'
    - task: AzureAppServiceSettings@1
      inputs:
        azureSubscription:  $(azureSubscription)
        appName: 'mis-Project-service-shriviraj-qa'
        resourceGroupName: $(QAResourceGroup)
        appSettings: |
          [
                  {
                    "name": "ASPNETCORE_ENVIRONMENT",
                    "value": "shrivirajQA",
                    "slotSetting": false
                  }
          ]
    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(azureSubscription)
        appType: 'webApp'
        appName: 'mis-Project-service-shriviraj-qa'
        package:  $(Build.ArtifactStagingDirectory)/**/*.zip


- stage: 'Prod'
  jobs: 
  - job: 'Prod'
  - deployment: DeployToProdDeployment
    displayName: 'Deploy to Prod Deployment'
    environment: 'ShrivirajProd'
    strategy:
        runOnce:
          deploy:
            steps:  
            - task: DownloadPipelineArtifact@2
              inputs:
                      buildType: 'current'
                      artifactName: $(artifactName)
                      targetPath: '$(Build.ArtifactStagingDirectory)'
            - task: AzureAppServiceSettings@1
              inputs:
                azureSubscription:  $(azureSubscription)
                appName:  'mis-Project-service-shriviraj-prod'
                resourceGroupName: $(ProdResourceGroup)
                appSettings: |
                  [
                          {
                            "name": "ASPNETCORE_ENVIRONMENT",
                            "value": "shrivirajProd",
                            "slotSetting": false
                          }
                  ]
            - task: AzureWebApp@1
              inputs:
                azureSubscription: $(azureSubscription)
                appType: 'webApp'
                appName: 'mis-Project-service-shriviraj-prod'
                package: $(Build.ArtifactStagingDirectory)/**/*.zip


