name: Build

on: 
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.102

      - name: Restore dependencies
        run: dotnet restore MIS.Services.Project.Api/MIS.Services.Project.Api.csproj

      - name: Build
        run: dotnet build MIS.Services.Project.Api/MIS.Services.Project.Api.csproj
