name: Deploy .Net App to Azure Web App

on: 
  workflow_dispatch: 

jobs: 
  builds-and-deploy:
    uses: cybagedevops/mis-reusable/.github/workflows/mis-services-deployment-template-nileshv.yaml@main
    with:
      app-name: 'mis-project-service-nilesh-qa'
      resource-group: 'rg-mis-nilesh'
      keyVaultName: 'mis-keyvault-nilesh'
      resourceGroupNameKeyVault: 'rg-mis-persistent'
      ProjectPath: 'Mis.Services.Project.Api/Mis.Services.Project.Api.csproj'
      appSettings: 'nileshQA'
      buildProject: 'true'
     
    secrets: inherit
