name: MIS-PROJECT-SERVICE-BUILD-DEPLOY-$(Year:yyyy).$(Month).$(DayOfMonth)-$(rev:rr)

trigger:
- none

pool: 
 name: Azure VM Agent Pool

resources:
  pipelines:
      - pipeline: mis-project-service-yash
        source: MIS-LEAVE-MANAGEMENT-SERVICE-BUILD-DEPLOY-20231123-01
        trigger: true

  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main
      
variables:
 group: MIS-DB-YASH

stages:
 - stage: 'Build_and_Publish'
   displayName: Build and Publish Package 
   jobs:
   - job: 'Build_Publish'
     displayName: Build and Publish
     steps:
 
     - template: .azure/pipelines/yash/build-deploy-app-service.yml@mis-reusable

       parameters: 
        serviceName: 'Project'
         
 - stage: 'QA'
   displayName: QA Deployment
   jobs:
   - job: 'QA'
     displayName: QA Deployment
     steps:
    
     - template: .azure/pipelines/yash/deploy-app-service.yml@mis-reusable

       parameters:
        azureSubscription: $(azureSubscription)
        keyVaultName: $(keyVaultName)
        keyVaultResourceGroupName: $(keyVaultResourceGroupName)
        allServicesResourceGroupName: $(resoureceGroupNameQA)
        azureAppName: 'mis-project-svc-yash-qa'
        serviceName: 'Project'
        environmentName: $(environmentNameQA)

 - stage: 'Prod'
   displayName: Production Deployment
   jobs:
   - job: 'Prod'
     displayName: Production Deployment
     steps:
    
     - template: .azure/pipelines/yash/deploy-app-service.yml@mis-reusable
      
       parameters:
        azureSubscription: $(azureSubscription)
        keyVaultName: $(keyVaultName)
        keyVaultResourceGroupName: $(keyVaultResourceGroupName)
        allServicesResourceGroupName: $(resoureceGroupNameProd)
        azureAppName: 'mis-project-svc-yash-prod'
        serviceName: 'Project'
        environmentName: $(environmentNameProd)