name: MIS-PROJECT-SERVICE-DOCKER-IMAGE-BUILD-YASH-$(Year:yyyy).$(Month).$(DayOfMonth)-$(rev:rr)


trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 
    jobs:
    - job: 
      steps:
      
     
          - task: Docker@2
            inputs:
              containerRegistry: $(containerRegistry)
              repository: 'mis-project-service-yash'
              tags: latest
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
